name: PR testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  USERNAME: ${{ github.actor }}
  EMAIL: ${{ github.actor}}@users.noreply.github.com
  GITHUB_CONTEXT: ${{ toJson(github.event) }}

jobs:
  create-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sapiderman/seed-go
          token: ${{ secrets.AUTO_PR_TOKEN }}

      - name: Update some file
        run: |
          rm README.md
          git diff-index --quiet HEAD -- || { echo "ERROR: Dirty repository found"; git status --porcelain; }          
          echo "username: $USERNAME"
          echo "username: $EMAIL"
          git config --global user.name "$USERNAME"
          git config --global user.email "$EMAIL"
          git add .
          git commit -m "yeaah updated" 
          git diff-index --quiet HEAD -- || { echo "ERROR: Dirty repository found"; git status --porcelain; exit 1; }

      # - name: Print Github Contexts
      #   run: echo "$GITHUB_CONTEXT"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.AUTO_PR_TOKEN }}
          commit-message: Update monika-config-schema
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          base: main
          push-to-fork: sapiderman/seed-go
          branch: test/autopr-workflow
          title: "[PR] testing autoPR"
          body: |
            In this PR:
            - 1. workflow
            - 2. fork target

          draft: false
          delete-branch: true

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
