# This worklofw will trigger on a push to main when the file "monika-config-schema.json" is updated
# 1. Checkout the schemastore fork
# 2. Refresh it from upstream
# 3. Create a PR for the json update

name: Auto PR to Schemastore/schemastore.git

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-auto-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: SchemaStore/schemastore
          token: ${{ secrets.AUTO_PR_TOKEN }}
          ref: master

      - name: Sync local fork
        run: |
          git remote add upstream https://github.com/SchemaStore/schemastore
          git pull upstream master --ff-only
          git push origin master

      - name: Update schema file
        run: |
          cd src/schemas/json
          rm monika-config-schema.json
          wget https://raw.githubusercontent.com/hyperjumptech/monika/main/src/monika-config-schema.json
      
      - name: Test schema 
        run : |
          make

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
