name: PR to seed-nodejs

on:
  workflow_dispatch:
  push:
    branches: 
      - main
     
jobs:
  create-PR:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: sapiderman/seed-go
      
      - name: Update file
        run: |
          rm README.md
          wget https://raw.githubusercontent.com/sapiderman/test-repo/main/README.md
          cat README.md          

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with: 
          token: $${{ secrets.GITHUB_TOKEN }}
          commit-message: Updating Schema JSON file
          committer: GitHub <noreply@github.com>
          # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: wonderwoman
          base: main
          branch: feat/Update-monika-schema
          
          title: '[PR] Update config schema'
          body: |
            In this PR:
            - testing auto PR
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          
          draft: false
          delete-branch: true

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"



